Account setup
mkyl/Physical-Web-CMS-Android pull request #1
Opened 2017-06-13 19:28 UTC by mkyl

This pull request is to fulfill technical deliverable 1, "Using the Google Drive API, the Android app will allow the user to authorize their Google account so the app can upload content."

Find a short video demo of this code here: https://youtu.be/HKnuS_gt0T4

2017-06-19 09:38 UTC, jelcaf requested changes
Hi @mkyl, good job! But I can't run the code in my environment. In the comments you can find the request changes (one of them fix the crash in the app).

2017-06-19 09:38 UTC, jelcaf commented on app/src/main/java/com/physical_web/cms/physicalwebcms/DriveSetupActivity.java
> +        this.findViewById(R.id.textViewWarning).setVisibility(View.INVISIBLE);
Why you are using `this.findById` and in some cases `findById` (without `this`) ?

2017-06-19 09:38 UTC, jelcaf commented on app/src/main/java/com/physical_web/cms/physicalwebcms/SetupManager.java
> +            context.startActivity(welcomeIntent);
If I run the code...  crash the app.

![screen shot 2017-06-19 at 10 32 01 am](https://user-images.githubusercontent.com/1067352/27278874-971d9fe8-54da-11e7-9544-b87fcf7a3b6c.png)

I'm not quite sure, but if you use `welcomeIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);` before start the new activity could fix the problem.

2017-06-19 15:35 UTC, mkyl commented on app/src/main/java/com/physical_web/cms/physicalwebcms/SetupManager.java
> +            context.startActivity(welcomeIntent);
What version of Android are you running?

2017-06-19 16:30 UTC, mkyl commented on app/src/main/java/com/physical_web/cms/physicalwebcms/DriveSetupActivity.java
> +        this.findViewById(R.id.textViewWarning).setVisibility(View.INVISIBLE);
Fixed.

2017-06-19 16:31 UTC, mkyl commented on app/src/main/java/com/physical_web/cms/physicalwebcms/SetupManager.java
> +            context.startActivity(welcomeIntent);
I think a545d15 should fix this bug

2017-06-19 16:35 UTC, mkyl commented
Thanks for the feedback. Let me know if there is anything else to improve. 

Also I wanted to note that this branch doesn't really have tests because I thought any tests for drive sign-up would be difficult to setup and fragile/inconsistent. I've written tests for the other parts of the setup which are in a different branch.

2017-06-20 07:41 UTC, jelcaf commented
Awesome!! You can merge it.

2017-06-20 07:44 UTC, jelcaf approved these changes

2017-06-20 16:12 UTC, merged